### ISSUE TITLE
Display on monitors?

### ISSUE THREAD

**Issue by ResqDiver1317** [bjm021/wave-amp2#1]
Is it possible to display the GUI on a group of monitors or is it only available inside the computer itself? Would love to have monitors setup so anyone hanging out on my patio can see what's playing

**Comment by JustSxm** [comment]
up

**Comment by JustSxm** [comment]
For anyone coming by here, I've quickly made an adaptation so it works on a monitor. The monitor must be on a modem and it should work! 

https://github.com/JustSxm/wave-amp2

**Comment by bjm021** [comment]
Sorry for the late reply. I haven't worked on this project for some time and for some reason I didn't receive a notification from GitHub about this issue.

The original should run just fine by using the monitor command.
Example: monitor right wave-amp2

At least for me it used to work on monitors with CC:Tweaked on 1.16.4

**Comment by bjm021** [comment]
I just confirmed it works with CC: Tweaked 1.101.1 on 1.19.2 (Forge 43.2.0) with the monitor command.
