### ISSUE TITLE
No support for banjos

### ISSUE THREAD

**Issue by MakkuroJoKeRGod** [bjm021/wave-amp2#3]
I notice that the script does not support banjo tracks.

I've tried adding "banjo" at the line here but that didn't seem to fix the issue.
![image](https://user-images.githubusercontent.com/49630370/216807357-47077d02-8ef3-4343-b21c-d913f3936d7e.png)
I have very minimal knowledge on how this script works, so maybe there's something I missing.

**Comment by bjm021** [comment]
Thanks for the hint, I just added support for all current instruments in the latest commit.
