### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Dibucci** [bjm021/wave-amp2#8]
Do the notes and the TPS have to stay within the range for when playing on actual noteblocks or is there no limit to the TPS and how high and low the notes can go?

Also, if there is a limit, is there a way to bypass is?

**Comment by bjm021** [comment]
According to the [CC:Tweaked Documentation for playNote()](https://tweaked.cc/peripheral/speaker.html#v:playNote), it is sadly not possible to play pitches that aren't normally in the game. But the timing can be adjusted (faster than normal). The /playsound command doesn't seem helpful either, the pitch range is 0.5 to 2 and it seems like 2 is the highest, and 0.5 the lowest pitch that a Noteblock can normally play.
