### ISSUE TITLE
(IDK WHERE TO PUT THIS) How to Install Custom Songs

### ISSUE THREAD

**Issue by AxoYoutube** [bjm021/wave-amp2#9]
I have been scrambling and it doesn't seem you guys say or explain how to import custom songs. How do i go about that?

**Comment by bjm021** [comment]
Hello, once again, sorry for the late reply, I'm currently in the middle of my bachelor thesis and don't really have much free time for personal projects.

The script is compatible with the .nbs format. You can read more about it [here](https://opennbs.org/nbs).

It works similar to MIDI files.

You can use [Open Noteblock Studio](https://opennbs.org/) to create/import custom songs. 
Please refer to their website for more information.
